# MAIN base
baseURL = "https://boisterous-panda-9784ee.netlify.app/"
languageCode = "en-us"
title = "Cyberaas | Managed Detection & Remediation Service"
theme = "apsho"

[taxonomies]
    tag = "tags"
    category = "categories"
    archive = "archive"

# Navigation Bar
[[menu.main]]
    name = "Home"
    url = ""
    weight = 1
[[menu.main]]
    name = "Our Services"
    url = "services"
    weight = 2
[[menu.main]]
    name = "About Us"
    url = "about"
    weight = 3
[[menu.main]]
    name = "Blog"
    url = "blog"
    weight = 4
[[menu.main]]
    name = "Contact Us"
    url = "contact"
    weight = 45

# Footer Sitemap
[[menu.sitemap]]
    name = "Home"
    url = "#"
    weight = 1
[[menu.sitemap]]
    name = "Latest Article"
    url = "/blog"
    weight = 2
[[menu.sitemap]]
    name = "Privacy & Policy"
    url = "/privacy"
    weight = 3
[[menu.sitemap]]
    name = "Contact"
    url = "/contact"
    weight = 4

# Footer Address
[params.address]
address1 = "7 Temasek Boulevard"
address2 = "#12-07 Suntec Tower One"
address3 = " Singapore 038987"
email = "contact@cyberaas.io"


# Enable and disable widgets for the right sidebar
[params.widgets]
    recent_articles = true
    categories = true
    archive = true
    tag_cloud = true

# Footer Social
[params.social]
facebook = "https://www.facebook.com/pg/staticmania"
twitter = "https://twitter.com/static_mania"
github = "https://github.com/StaticMania"

[params]

# Header
logo = "images/logo.png"
formspreeURL = "https://formspree.io/mknyovwz"
googleAnalytics = "UA-175025671-2"

# Footer
footerTitle = "Get the latest app updates"
copyright1 = "All right reserved"
copyright2 = "Copyright © Cyberaas {year}"

#contact
email = "help@staticmania.com"